version: "3"
services:
  mirai:
    build: ./mirai
    container_name: mirai
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
  bot:
    build: ./deploy
    container_name: mirai_bot
    restart: always
    depends_on:
      - mirai
      - redis
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.yml:/app/config.yml
  redis:
    image: redis
    container_name: mirai_redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf